name: Upload artifacts

on:
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Upload artifacts v3
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-v3
          path: README.md
      - name: Upload artifacts v4
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-v4
          path: README.md
